# .github/workflows/ci.yml

name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Clone gohugoio/hugoBasicExample repository'
      run: |
        git clone https://github.com/gohugoio/hugoBasicExample.git
        cd hugoBasicExample
        mkdir -p themes/meme

    - name: 'Check out MemE into themes/meme folder'
      uses: actions/checkout@v2
      with:
        path: hugoBasicExample/themes/meme

    - name: 'Setup MemE'
      run: |
        cd hugoBasicExample
        rm -rf config*
        cp themes/meme/exampleSite/config.toml .

    - name: 'Install Hugo'
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest
        extended: true

    - name: 'Build site'
      run: |
        cd hugoBasicExample
        sed -i 's/relativeURLs = false/relativeURLs = true/g' config.toml
        hugo --gc --minify --cleanDestinationDir

    - name: 'Deploy to GitHub Pages'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: hugoBasicExample/public
        force_orphan: true
